# Generated by Django 6.0.4 on 2026-04-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('summary', models.TextField(blank=True, verbose_name='文档简介')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='文档文件')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套餐名称')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='副标题')),
                ('description', models.TextField(verbose_name='套餐介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='划线价')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('documents', models.ManyToManyField(blank=True, related_name='packages', to='store.document', verbose_name='包含文档')),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('buyer_name', models.CharField(blank=True, max_length=100, verbose_name='购买人')),
                ('buyer_contact', models.CharField(blank=True, max_length=120, verbose_name='联系方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.package', verbose_name='购买套餐')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
