# Generated by Django 6.0.4 on 2026-04-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_trade_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='平台订单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='支付方式'),
        ),
    ]
