# Generated by Django 6.0.4 on 2026-04-15 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_gateway_trade_no_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='购买数量'),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_mode',
            field=models.CharField(choices=[('docs', '文档套餐'), ('stock', '按条发货')], default='docs', max_length=20, verbose_name='发货模式'),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='发货内容')),
                ('is_sold', models.BooleanField(default=False, verbose_name='是否已售')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='售出时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='store.package', verbose_name='所属商品')),
                ('sold_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='store.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '按条库存',
                'verbose_name_plural': '按条库存',
                'ordering': ['id'],
            },
        ),
    ]
