# Generated by Django 6.0.4 on 2026-04-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_quantity_package_delivery_mode_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='提取密码'),
        ),
        migrations.AddField(
            model_name='package',
            name='items_per_unit',
            field=models.PositiveIntegerField(default=1, verbose_name='每份发货条数'),
        ),
    ]
