# Generated by Django 6.0.4 on 2026-04-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_pickup_password_package_items_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stock_mode',
            field=models.CharField(choices=[('line', '按条售卖'), ('group', '按组售卖')], default='line', max_length=20, verbose_name='库存售卖模式'),
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_mode',
            field=models.CharField(choices=[('docs', '文档套餐'), ('stock', '库存发货')], default='docs', max_length=20, verbose_name='发货模式'),
        ),
    ]
