# Generated by Django 6.0.4 on 2026-04-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_package_stock_mode_alter_package_delivery_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['id'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('issue', '支付成功待处理'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(verbose_name='商品介绍'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=200, verbose_name='商品名称'),
        ),
    ]
