# Generated by Django 6.0.4 on 2026-04-17 15:52

import django.db.models.deletion
from django.db import migrations, models


def seed_agent_floor_prices(apps, schema_editor):
    Package = apps.get_model('store', 'Package')
    Package.objects.filter(
        delivery_mode='stock',
        stock_mode='line',
    ).update(agent_floor_price='0.30')
    Package.objects.filter(
        delivery_mode='stock',
        stock_mode='group',
    ).update(agent_floor_price='25.00')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_package_options_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=255, verbose_name='登录密码')),
                ('nickname', models.CharField(max_length=80, verbose_name='代理昵称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='代理编号')),
                ('wechat_id', models.CharField(blank=True, max_length=120, verbose_name='微信号')),
                ('alipay_account', models.CharField(blank=True, max_length=120, verbose_name='支付宝账号')),
                ('payee_name', models.CharField(blank=True, max_length=80, verbose_name='收款姓名')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '已开通'), ('disabled', '已禁用')], default='pending', max_length=20, verbose_name='代理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='开通时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间')),
            ],
            options={
                'verbose_name': '代理',
                'verbose_name_plural': '代理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='agent_base_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='代理底价快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_code_snapshot',
            field=models.CharField(blank=True, max_length=32, verbose_name='代理编号快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_profit_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='代理利润快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_sale_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='代理售价快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='代理结算时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_settlement_status',
            field=models.CharField(choices=[('pending', '待结算'), ('settled', '已结算')], default='pending', max_length=20, verbose_name='代理结算状态'),
        ),
        migrations.AddField(
            model_name='package',
            name='agent_floor_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='代理底价'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.agent', verbose_name='关联代理'),
        ),
        migrations.CreateModel(
            name='AgentPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='代理售价')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_prices', to='store.agent', verbose_name='代理')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_prices', to='store.package', verbose_name='商品')),
            ],
            options={
                'verbose_name': '代理价格',
                'verbose_name_plural': '代理价格',
                'ordering': ['package__id'],
                'unique_together': {('agent', 'package')},
            },
        ),
        migrations.RunPython(seed_agent_floor_prices, migrations.RunPython.noop),
    ]
