# Generated by Django 6.0.4 on 2026-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_agent_order_agent_base_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='公开电话'),
        ),
        migrations.AddField(
            model_name='agent',
            name='contact_qq',
            field=models.CharField(blank=True, max_length=40, verbose_name='公开QQ'),
        ),
        migrations.AddField(
            model_name='agent',
            name='contact_wechat',
            field=models.CharField(blank=True, max_length=120, verbose_name='公开微信号'),
        ),
    ]
