# Generated by Django 6.0.4 on 2026-04-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_agent_register_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='绑定邮箱'),
        ),
        migrations.AddField(
            model_name='agent',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='agent',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邮箱验证时间'),
        ),
        migrations.CreateModel(
            name='AgentEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('purpose', models.CharField(choices=[('register', '代理注册'), ('bind', '绑定邮箱'), ('reset', '找回密码')], max_length=20, verbose_name='用途')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to='store.agent', verbose_name='关联代理')),
            ],
            options={
                'verbose_name': '代理邮箱验证码',
                'verbose_name_plural': '代理邮箱验证码',
                'ordering': ['-created_at'],
            },
        ),
    ]
