"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
DEV_SECRET_KEY = 'django-insecure-lp$gbp6r9lyfz+%tou)j=nmeq))^j-t=czsmbhmpm)3hp$7%wz'
SECRET_KEY = os.getenv("SECRET_KEY", DEV_SECRET_KEY)
if not DEBUG and SECRET_KEY == DEV_SECRET_KEY:
    raise ImproperlyConfigured("生产环境缺少 SECRET_KEY 环境变量")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost,google888.asia,www.google888.asia",
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://google888.asia,https://www.google888.asia",
    ).split(",")
    if origin.strip()
]

SITE_BASE_URL = os.getenv("SITE_BASE_URL", "https://google888.asia").rstrip("/")

# Trust the reverse proxy so Django treats Cloudflare/Nginx HTTPS requests as secure.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'store.middleware.SimpleRateLimitMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

CKKP_GATEWAY = os.getenv("CKKP_GATEWAY", "https://www.ckkp.cn/submit.php")
CKKP_MAPI_GATEWAY = os.getenv("CKKP_MAPI_GATEWAY", "https://www.ckkp.cn/mapi.php")
CKKP_QUERY_GATEWAY = os.getenv("CKKP_QUERY_GATEWAY", "https://www.ckkp.cn/api.php?act=order")
CKKP_PID = os.getenv("CKKP_PID", "1002")
CKKP_TYPE = os.getenv("CKKP_TYPE", "")
CKKP_SIGN_TYPE = os.getenv("CKKP_SIGN_TYPE", "MD5")
CKKP_MD5_KEY = os.getenv("CKKP_MD5_KEY", "311nNqbQOq1g1566nzNN85q713vkblg6")
CKKP_PRIVATE_KEY_PATH = os.getenv("CKKP_PRIVATE_KEY_PATH", "/etc/docstore/ckkp/merchant_private_key.pem")
CKKP_PLATFORM_PUBLIC_KEY_PATH = os.getenv("CKKP_PLATFORM_PUBLIC_KEY_PATH", "/etc/docstore/ckkp/platform_public_key.pem")
MAIL_GATEWAY_SYNC_ENABLED = os.getenv("MAIL_GATEWAY_SYNC_ENABLED", "True").lower() == "true"
MAIL_GATEWAY_SYNC_URL = os.getenv(
    "MAIL_GATEWAY_SYNC_URL",
    "https://fbvjdjcf.asia/api/internal/mailbox-whitelist-sync",
).strip()
MAIL_GATEWAY_SYNC_TOKEN = os.getenv(
    "MAIL_GATEWAY_SYNC_TOKEN",
    "",
).strip()

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "192.161.173.109").strip()
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@bbacyd.asia").strip()
AGENT_EMAIL_CODE_EXPIRE_MINUTES = int(os.getenv("AGENT_EMAIL_CODE_EXPIRE_MINUTES", "10"))
AGENT_EMAIL_CODE_MAX_ATTEMPTS = int(os.getenv("AGENT_EMAIL_CODE_MAX_ATTEMPTS", "8"))
AGENT_LOGIN_PASSWORD_MIN_LENGTH = int(os.getenv("AGENT_LOGIN_PASSWORD_MIN_LENGTH", "8"))
TRUSTED_PROXY_IPS = {
    ip.strip()
    for ip in os.getenv("TRUSTED_PROXY_IPS", "127.0.0.1,::1").split(",")
    if ip.strip()
}

APP_RATE_LIMIT_RULES = [
    {
        "name": "admin-login",
        "pattern": r"^/admin/login/$",
        "methods": ["POST"],
        "limit": 8,
        "window": 600,
        "block_message": "10 分钟",
    },
    {
        "name": "pickup-lookup",
        "pattern": r"^/pickup/$",
        "methods": ["POST"],
        "limit": 6,
        "window": 300,
        "block_message": "5 分钟",
    },
    {
        "name": "pickup-order",
        "pattern": r"^/orders/\d+/pickup/$",
        "methods": ["POST"],
        "limit": 6,
        "window": 300,
        "block_message": "5 分钟",
    },
    {
        "name": "create-order",
        "pattern": r"^/packages/\d+/buy/$",
        "methods": ["POST"],
        "limit": 12,
        "window": 300,
        "block_message": "5 分钟",
    },
    {
        "name": "start-payment",
        "pattern": r"^/orders/\d+/pay/$",
        "methods": ["POST"],
        "limit": 10,
        "window": 300,
        "block_message": "5 分钟",
    },
    {
        "name": "agent-login",
        "pattern": r"^/agent/login/$",
        "methods": ["POST"],
        "limit": 8,
        "window": 600,
        "block_message": "10 分钟",
    },
    {
        "name": "agent-email-code",
        "pattern": r"^/agent/email-code/$",
        "methods": ["POST"],
        "limit": 6,
        "window": 600,
        "block_message": "10 分钟",
    },
    {
        "name": "agent-password-reset",
        "pattern": r"^/agent/password-reset/$",
        "methods": ["POST"],
        "limit": 6,
        "window": 600,
        "block_message": "10 分钟",
    },
    {
        "name": "agent-bind-email",
        "pattern": r"^/agent/bind-email/$",
        "methods": ["POST"],
        "limit": 6,
        "window": 600,
        "block_message": "10 分钟",
    },
    {
        "name": "agent-password",
        "pattern": r"^/agent/password/$",
        "methods": ["POST"],
        "limit": 6,
        "window": 600,
        "block_message": "10 分钟",
    },
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
